# Generated by Django 4.1 on 2022-11-01 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_monthlygoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('week_number', models.IntegerField(default=1)),
                ('weekly_hours', models.IntegerField(default=20)),
                ('monthly_hours', models.IntegerField(default=80)),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyGoal',
        ),
    ]
