# Generated by Django 4.1 on 2022-11-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_hourlygoals_delete_monthlygoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlygoals',
            name='monthly_hours',
        ),
    ]
